[project]
name = "nyc-accidents-2020"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "iconlit", email = "akpaesudavid@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "geopandas>=1.2.0",
    "jupyterlab>=4.6.4",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
nyc-accidents-2020 = "nyc_accidents_2020:main"


